//! Downloads, verifies, and embeds the vendored ffmpeg/ffprobe/yt-dlp
//! binaries described in `vendor.toml` (only when the `bundled` feature is
//! active - `slim` builds skip this entirely and rely on PATH/manual
//! detection at runtime instead).
//!
//! Downloads are cached in `.vendor-cache/` (gitignored) next to this file,
//! keyed by the pinned URL, so incremental builds never re-fetch. Set
//! `MEDIAKIT_VENDOR_DIR` to a directory of pre-downloaded, correctly-named
//! archives to build fully offline (the cache dir also doubles as this: you
//! can pre-populate `.vendor-cache/` by hand).

use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct VendorManifest {
    ffmpeg: HashMap<String, VendorEntry>,
    ytdlp: HashMap<String, VendorEntry>,
}

#[derive(Debug, Deserialize)]
struct VendorEntry {
    version: String,
    url: String,
    sha256: String,
    archive_kind: String,
    #[serde(default)]
    ffmpeg_path_in_archive: Option<String>,
    #[serde(default)]
    ffprobe_path_in_archive: Option<String>,
    #[serde(default)]
    license: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=vendor.toml");
    println!("cargo:rerun-if-env-changed=MEDIAKIT_VENDOR_DIR");

    let bundled = std::env::var("CARGO_FEATURE_BUNDLED").is_ok();
    if !bundled {
        // Slim build: nothing to download or embed. `core::vendor`'s
        // `#[cfg(feature = "bundled")]` module is compiled out entirely, so
        // it never tries to `include_bytes!` the files we'd otherwise
        // produce here.
        return;
    }

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").expect("CARGO_CFG_TARGET_OS not set");
    let target_arch =
        std::env::var("CARGO_CFG_TARGET_ARCH").expect("CARGO_CFG_TARGET_ARCH not set");
    let platform_key = match (target_os.as_str(), target_arch.as_str()) {
        ("linux", "x86_64") => "linux-x86_64",
        ("windows", "x86_64") => "windows-x86_64",
        _ => {
            println!(
                "cargo:warning=mediakit-core: no vendored binaries pinned for {target_os}-{target_arch}; \
                 building without bundling. Runtime will fall back to PATH/manual detection."
            );
            return;
        }
    };

    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    let cache_dir = manifest_dir.join(".vendor-cache");
    fs::create_dir_all(&cache_dir).expect("create .vendor-cache");

    let vendor_toml_path = manifest_dir.join("vendor.toml");
    let vendor_toml_text = fs::read_to_string(&vendor_toml_path).expect("read core/vendor.toml");
    let vendor: VendorManifest = toml::from_str(&vendor_toml_text).expect("parse core/vendor.toml");

    let ffmpeg_entry = vendor
        .ffmpeg
        .get(platform_key)
        .unwrap_or_else(|| panic!("vendor.toml has no [ffmpeg.{platform_key}] entry"));
    let ytdlp_entry = vendor
        .ytdlp
        .get(platform_key)
        .unwrap_or_else(|| panic!("vendor.toml has no [ytdlp.{platform_key}] entry"));

    let ffmpeg_archive = fetch_and_verify(ffmpeg_entry, &cache_dir);
    let ytdlp_raw = fetch_and_verify(ytdlp_entry, &cache_dir);

    let (ffmpeg_bin, ffprobe_bin) = extract_ffmpeg(&ffmpeg_archive, ffmpeg_entry);

    write_compressed(&out_dir.join("ffmpeg.zst"), &ffmpeg_bin);
    write_compressed(&out_dir.join("ffprobe.zst"), &ffprobe_bin);
    write_compressed(&out_dir.join("ytdlp.zst"), &ytdlp_raw);

    let generated = format!(
        "// @generated by build.rs - do not edit.\n\
         pub const FFMPEG_VERSION: &str = {:?};\n\
         pub const FFMPEG_SHA256: &str = {:?};\n\
         pub const FFMPEG_LICENSE: &str = {:?};\n\
         pub const YTDLP_VERSION: &str = {:?};\n\
         pub const YTDLP_SHA256: &str = {:?};\n\
         pub const YTDLP_LICENSE: &str = {:?};\n",
        ffmpeg_entry.version,
        ffmpeg_entry.sha256,
        ffmpeg_entry.license.as_deref().unwrap_or("unknown"),
        ytdlp_entry.version,
        ytdlp_entry.sha256,
        ytdlp_entry.license.as_deref().unwrap_or("unknown"),
    );
    fs::write(out_dir.join("vendor_generated.rs"), generated).expect("write vendor_generated.rs");

    println!(
        "cargo:warning=mediakit-core: bundling ffmpeg {} and yt-dlp {} ({})",
        ffmpeg_entry.version, ytdlp_entry.version, platform_key
    );
}

fn write_compressed(path: &Path, data: &[u8]) {
    let compressed = zstd::encode_all(data, 19).expect("zstd compress vendored binary");
    fs::write(path, compressed).expect("write compressed vendored binary");
}

/// Download (or reuse a cached copy of) `entry.url`, verify its SHA-256
/// against `entry.sha256`, and return the raw bytes. Panics loudly on any
/// checksum mismatch - a corrupted or tampered vendored binary must never
/// silently ship.
fn fetch_and_verify(entry: &VendorEntry, cache_dir: &Path) -> Vec<u8> {
    let filename = entry
        .url
        .rsplit('/')
        .next()
        .expect("vendor url has no filename");
    let cache_path = cache_dir.join(filename);

    let bytes = if let Ok(manual_dir) = std::env::var("MEDIAKIT_VENDOR_DIR") {
        let manual_path = PathBuf::from(manual_dir).join(filename);
        fs::read(&manual_path).unwrap_or_else(|e| {
            panic!(
                "MEDIAKIT_VENDOR_DIR is set but couldn't read {}: {e}",
                manual_path.display()
            )
        })
    } else if let Ok(cached) = fs::read(&cache_path) {
        cached
    } else {
        println!("cargo:warning=mediakit-core: downloading {}", entry.url);
        let downloaded = download(&entry.url);
        fs::write(&cache_path, &downloaded).expect("write vendor cache file");
        downloaded
    };

    let actual_sha256 = sha256_hex(&bytes);
    if actual_sha256 != entry.sha256 {
        // Never trust a cached/manual file that fails verification: remove
        // it so the next build attempt re-downloads instead of reusing a
        // bad cache entry forever.
        let _ = fs::remove_file(&cache_path);
        panic!(
            "checksum mismatch for {}: expected {}, got {actual_sha256}. \
             Refusing to bundle an unverified binary.",
            entry.url, entry.sha256
        );
    }

    bytes
}

fn download(url: &str) -> Vec<u8> {
    let mut response = ureq::get(url)
        .call()
        .unwrap_or_else(|e| panic!("failed to download {url}: {e}"));
    let mut buf = Vec::new();
    response
        .body_mut()
        .as_reader()
        .read_to_end(&mut buf)
        .unwrap_or_else(|e| panic!("failed to read response body from {url}: {e}"));
    buf
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex_encode(&hasher.finalize())
}

fn hex_encode(bytes: &[u8]) -> String {
    use std::fmt::Write;
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        write!(s, "{b:02x}").unwrap();
    }
    s
}

/// Extract the `ffmpeg`/`ffprobe` binaries from a downloaded archive.
fn extract_ffmpeg(archive_bytes: &[u8], entry: &VendorEntry) -> (Vec<u8>, Vec<u8>) {
    let ffmpeg_path = entry
        .ffmpeg_path_in_archive
        .as_deref()
        .expect("ffmpeg entry missing ffmpeg_path_in_archive");
    let ffprobe_path = entry
        .ffprobe_path_in_archive
        .as_deref()
        .expect("ffmpeg entry missing ffprobe_path_in_archive");

    match entry.archive_kind.as_str() {
        "tar_xz" => {
            let ffmpeg = extract_from_tar_xz(archive_bytes, ffmpeg_path);
            let ffprobe = extract_from_tar_xz(archive_bytes, ffprobe_path);
            (ffmpeg, ffprobe)
        }
        "zip" => {
            let ffmpeg = extract_from_zip(archive_bytes, ffmpeg_path);
            let ffprobe = extract_from_zip(archive_bytes, ffprobe_path);
            (ffmpeg, ffprobe)
        }
        other => panic!("unknown archive_kind {other:?} in vendor.toml"),
    }
}

fn extract_from_tar_xz(archive_bytes: &[u8], entry_path: &str) -> Vec<u8> {
    let decompressed = xz2::read::XzDecoder::new(archive_bytes);
    let mut archive = tar::Archive::new(decompressed);
    for file in archive.entries().expect("read tar entries") {
        let mut file = file.expect("read tar entry");
        let path = file
            .path()
            .expect("tar entry path")
            .to_string_lossy()
            .into_owned();
        if path == entry_path {
            let mut buf = Vec::new();
            file.read_to_end(&mut buf).expect("read tar entry contents");
            return buf;
        }
    }
    panic!("archive did not contain expected entry {entry_path:?}");
}

fn extract_from_zip(archive_bytes: &[u8], entry_path: &str) -> Vec<u8> {
    let cursor = std::io::Cursor::new(archive_bytes);
    let mut archive = zip::ZipArchive::new(cursor).expect("read zip archive");
    let mut file = archive
        .by_name(entry_path)
        .unwrap_or_else(|_| panic!("zip archive did not contain expected entry {entry_path:?}"));
    let mut buf = Vec::new();
    file.read_to_end(&mut buf).expect("read zip entry contents");
    buf
}
